version: '2'
services:
  eaglet:
    build: .
    container_name: proxy_manager_sandbox
    networks:
      - servers_external_network
    ports:
      - "7000:80"
    env_file:
      - sandbox/.env
    tty: true
    volumes:
      - .:/usr/src/app
      - ./bin/log/proxy_manager_sandbox:/var/log/application/proxy_manager_sandbox
networks:
  servers_external_network:
    external: true